AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stori test
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  StoriTestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: stori-test/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        StoriTest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /send_email
            Method: post
      Environment:
        Variables:
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: "587"
          SMTP_FROM: ente011@gmail.com
          SMTP_USER: ente011@gmail.com
          SMTP_CODE: "mjjr aekr oikv qclv"
          DB_DRIVER: postgres
          DB_NAME: db_stori
          DB_USER: db_user
          DB_HOST: host.docker.internal
          DB_PORT: "5432"
          DB_PASS: db_pass
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StoriTestApi:
    Description: "API Gateway endpoint URL for Prod stage for Stori Test function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send_email/"
  StoriTestFunction:
    Description: "Stori Test Lambda Function ARN"
    Value: !GetAtt StoriTestFunction.Arn
  StoriTestFunctionIamRole:
    Description: "Implicit IAM Role created for Stori Test function"
    Value: !GetAtt StoriTestFunctionRole.Arn
